### ISSUE TITLE
Create a new tag `v0.1.5` from master

### ISSUE THREAD

**Issue by deepakmahakale** [coupa/resque-round-robin#4]
Can we please create a new tag `v0.1.5` from the master branch as with `v0.1.4` resque is locked to version `=1.19.0`

https://github.com/coupa/resque-round-robin/blob/76900384a63b1d5c1bef3d8c1b42d97fbc7dd198/resque-round-robin.gemspec#L11

The strict dependency is changed in the master branch 

https://github.com/coupa/resque-round-robin/blob/d47fcd4dd71e3b895209038d5ada7129dc783557/resque-round-robin.gemspec#L11

**Comment by edk** [comment]
Sorry for the delay, new tag created.  Thanks!

**Comment by deepakmahakale** [comment]
Thank you @edk
